### ISSUE TITLE
[BUG] ZeroDivisionError in anvi-gen-variability-profile

### ISSUE THREAD

**Issue by hdore** [merenlab/anvio#1948]
## Short description of the problem

I got a `ZeroDivisionError` when running `anvi-gen-variability-profile` with options `--engine CDN --quince-mode` (among others).

## anvi'o version

```
Anvi'o .......................................: hope (v7.1-dev)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2
```

## System info

I'm running Anvi'o on an HPC (linux).

## Detailed description of the issue

As explained on Slack, I got this error while running `anvi-gen-variability-profile` in the dev version. Here is the full command I used:
```
anvi-gen-variability-profile -p PROFILE.db \
                             -c MAGs-contigs.db \
                             -C NR_MAGs \
                             -b $BIN \
                             --samples-of-interest samples_names.list \
                             --engine CDN \
                             --min-occurrence 2 \
                             --quince-mode \
                             --compute-gene-coverage-stats \
                             --include-contig-names \
                             --include-site-pnps \
                             -o $BIN"_SCV_profiles.txt"
```
And here is the error in the log file:
```
[28 Jun 22 05:03:34 Computing gene coverage stats] ... {consider --skip-g (...)
✖ anvi-gen-variability-profile encountered an error after 0:43:42.330064
Traceback (most recent call last):
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/github/anvio/bin/anvi-gen-variability-profile", line 92, in <module>
    main(args)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/github/anvio/anvio/terminal.py", line 875, in wrapper
    program_method(*args, **kwargs)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/github/anvio/bin/anvi-gen-variability-profile", line 34, in main
    variability_engine.process()
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/github/anvio/anvio/variabilityops.py", line 1753, in process
    func(**kwargs)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/github/anvio/anvio/variabilityops.py", line 2012, in compute_gene_coverage_fields
    self.data['mean_normalized_coverage'] = self.data['coverage'] / self.data['gene_coverage']
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/arraylike.py", line 116, in __truediv__
    return self._arith_method(other, operator.truediv)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/series.py", line 5526, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 224, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 166, in _na_arithmetic_op
    result = func(left, right)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 69, in _evaluate_standard
    return op(a, b)
ZeroDivisionError: float division by zero
```
I guess `self.data['gene_coverage']` is 0 and this causes the error. Could it be because I used `--engine SCV` with `--quince-mode?`

Thank you for your help!

hdore

**Comment by meren** [comment]
Hi @hdore,

Thanks for the report. I realized this happens this happens when the user uses `--include-site-pnps` flag without any
scrutiny of the coverage of CDN sites across samples, such as with a `--min-coverage-in-each-sample INT` parameter, in which case a position with 0 coverage can explode the algorithm. We never use `anvi-gen-variability-profile` without enforcing a minimum coverage cutoff, that's why we must have missed this case.

The issue must be fixed in the main development branch. Please try it after a `git pull` :)


Best,

**Comment by hdore** [comment]
Hi @meren, 
Thanks for looking into it. I guess my approach is "testing with all options to get a maximum of information" and see if I can handle it.
I'll try it as soon as I can, and will let you know!
Best,
hdore

**Comment by hdore** [comment]
Hello @meren,
Unfortunately, I still get the same error for some of my MAGs with the latest version.
I might just remove the `--include-site-pnps` option for now, but wanted to let you know.
Best,
hdore

**Comment by meren** [comment]
it is almost impossible for you to get the same error, @hdore, since the error is caused by division by zero, but the code will never go into that routine if the coverage is zero. Are you sure you were able to git pull successfully and you indeed have the latest version of the active development branch?

**Comment by hdore** [comment]
Hi @meren,
I cannot `git pull` myself, but asked the person in charge of it to do it and they did. I checked that the changes from #[c5d419b5](https://github.com/merenlab/anvio/commit/c5d419b570466959ff4d872115c4688b0778facd) were present in the script `variabilityops.py`.
I'm very far from understanding this script, but from the error log the error seems to be raised at line 2012
` File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/github/anvio/anvio/variabilityops.py", line 2012, in compute_gene_coverage_fields
    self.data['mean_normalized_coverage'] = self.data['coverage'] / self.data['gene_coverage']`

So maybe the error could come from the use of `--compute-gene-coverage-stats` with `--quince-mode` but without any filter on `--min-coverage-in-each-sample`? I can imagine a sample in which a gene is absent (coverage is 0 for the position and for the whole gene) but the position is reported in that sample because of `--quince-mode`. I don't know if this is already handled by the script.

**Comment by hdore** [comment]
The error message is the same as above, I paste it here again (this time running with the latest changes):
```
[30 Jun 22 10:05:52 Computing gene coverage stats] ... {consider --skip-g (...)
✖ anvi-gen-variability-profile encountered an error after 0:47:31.208987
Traceback (most recent call last):
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/github/anvio/bin/anvi-gen-variability-profile", line 92, in <module>
    main(args)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/github/anvio/anvio/terminal.py", line 875, in wrapper
    program_method(*args, **kwargs)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/github/anvio/bin/anvi-gen-variability-profile", line 34, in main
    variability_engine.process()
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/github/anvio/anvio/variabilityops.py", line 1753, in process
    func(**kwargs)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/github/anvio/anvio/variabilityops.py", line 2012, in compute_gene_coverage_fields
    self.data['mean_normalized_coverage'] = self.data['coverage'] / self.data['gene_coverage']
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/arraylike.py", line 116, in __truediv__
    return self._arith_method(other, operator.truediv)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/series.py", line 5526, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 224, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 166, in _na_arithmetic_op
    result = func(left, right)
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/home/datawork-lmee-intranet-nos/conda-env/anvio-dev/anvio-dev/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 69, in _evaluate_standard
    return op(a, b)
ZeroDivisionError: float division by zero
```

I'd be happy to test your solution :)

**Comment by meren** [comment]
_(self-note: I JUST realized that yesterday I addressed *another* issue downstream to this problem without realizing that I wasn't actually fixing your issue, because my test dataset didn't have any genes with 0 coverage (only had some positions with 0 coverage))._

**Comment by meren** [comment]
Sigh :( Unfortunately that solution wouldn't work here, @hdore. I saw another problem that may be related to this and asked @ekiefl's to see if he can come up with a solution quickly. I'll get back to this.
