### ISSUE TITLE
[DISCUSSION] UI Improvements

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#2184]
I’m starting this issue to document problems with the revamped anvi’o interactive interface here for @metehaansever's consideration.

The changes are in the branch `ui-improvements`. If you are using anvio-dev, please consider switching to the `ui-improvements` branch,

```
cd ~/github/anvio
git checkout ui-improvements
```

Update your submodules,

```
git submodule update --init
```

Then, run any anvi'o project that works with the interactive interface, and report your observations under this thread.

---

You can always switch back to your regular main branch to back to how things were,

```
cd ~/github/anvio
git checkout master
git submodule update --init
```

**Comment by meren** [comment]
This is how the detailed taxonomy estimation panel looked like in the original version:

<img width="1239" alt="image" src="https://github.com/merenlab/anvio/assets/197307/49ba070b-f86f-4c79-aa3e-dda6f527e30e">

And how it looks like now (not very pretty, is it):

<img width="524" alt="image" src="https://github.com/merenlab/anvio/assets/197307/5d239b6e-2b9c-47b3-a1f0-f4edb3f7200b">

---

This is what happened when someone clicked on a bin in that window:

<img width="1190" alt="image" src="https://github.com/merenlab/anvio/assets/197307/b85f76e8-b5c9-4f4a-9d66-18cd3b9f3c34">

And this is what happens now (i.e., nothing :)):

<img width="483" alt="image" src="https://github.com/merenlab/anvio/assets/197307/a050bc17-a1ae-414a-8903-11555ec8b3b5">

**Comment by meren** [comment]
When there are no legends to be shown, under the legends section, in light gray, it should say,

"There are no legends to edit in this display."

It currently looks empty and confusing:

<img width="486" alt="image" src="https://github.com/merenlab/anvio/assets/197307/a3fdc6cb-e65e-4f73-88d4-2b19c888c204">

**Comment by meren** [comment]
Show grids button doesn't work (as in, you click on it, but grids are not shown for selections):

<img width="302" alt="image" src="https://github.com/merenlab/anvio/assets/197307/b45a9fe8-c219-4c7f-b12e-5adb01f32e15">

Plus, the color picker in the same control doesn't respond when clicked.

**Comment by metehaansever** [comment]
I'm on it! Thank you Meren

**Comment by meren** [comment]
This is the font-face in the original interface:

<img width="505" alt="image" src="https://github.com/merenlab/anvio/assets/197307/4b28d802-35cd-4a67-95e5-a2b25883782a">

And this is how it is in the `ui-improvements`:

<img width="535" alt="image" src="https://github.com/merenlab/anvio/assets/197307/0435ffc6-086b-4826-bd65-0aca620071d8">

**Comment by meren** [comment]
Please remove these two items from the options panel,

<img width="170" alt="image" src="https://github.com/merenlab/anvio/assets/197307/97828693-d107-4491-b97f-aa92cbd0bb8c">

And make custom margins turned on by default in the main panel as the following:

<img width="455" alt="image" src="https://github.com/merenlab/anvio/assets/197307/3d00bd9d-c2c7-450e-b98d-fab778b501e4">

There are multiple reasons for this. Options is a new panel, and this change affects the structure of the main panel, which is not what people are looking at when the button is clicked (in the old design it was under additional settings in the main panel, so it made it more intuitive). Now we have more space in the main panel, so there is no reason to not have them turned on by default.

**Comment by meren** [comment]
Please expand the width of the dropbox so the text fits (and replace 'leaf' with 'item' in the text):

<img width="237" alt="image" src="https://github.com/merenlab/anvio/assets/197307/a830735b-0102-444a-9845-9e81c72eab6d">

**Comment by metehaansever** [comment]
> This is the font-face in the original interface:
> 
> <img alt="image" width="505" src="https://private-user-images.githubusercontent.com/197307/288067105-4b28d802-35cd-4a67-95e5-a2b25883782a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODYxMjYsIm5iZiI6MTcwMTc4NTgyNiwicGF0aCI6Ii8xOTczMDcvMjg4MDY3MTA1LTRiMjhkODAyLTM1Y2QtNGE2Ny05NWU1LWEyYjI1ODgzNzgyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxNDE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTMzMjdkZTQ1YTZkYzJkMzRmYjc0MzViYzU3M2JhYWJhYjIzNzRmOGRjZmQ0OTIyNmU5N2UzOWM5ZmE0Nzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vtiTFlnGT6luM-IG83LtDtX8hvsGnIGExDh_xZWiF-k">
> And this is how it is in the `ui-improvements`:
> 
> <img alt="image" width="535" src="https://private-user-images.githubusercontent.com/197307/288067336-0435ffc6-086b-4826-bd65-0aca620071d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODYxMjYsIm5iZiI6MTcwMTc4NTgyNiwicGF0aCI6Ii8xOTczMDcvMjg4MDY3MzM2LTA0MzVmZmM2LTA4NmItNDgyNi1iZDY1LTBhY2E2MjAwNzFkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxNDE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTYzNjU2OTMzYzE5Mjg0OTNhODMyM2IxMmQ5YWUxNmU1YmYwMGI3N2Y0ZGY5YTMwMmFjODM0YmNiOWRhZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ERxoD3MMT55sEz_InH42M1HkNQbtbAMBR0OhT4PpACY">

Actually I did that in purpose. I replaced every font with "Montserrat", with some exceptions. The reason for this was to have the same typography everywhere.

**Comment by meren** [comment]
> Actually I did that in purpose. I replaced every font with "Montserrat", with some exceptions. The reason for this was to have the same typography everywhere.

And yet it is not working. This is how it looks on my interface right now:

<img width="385" alt="image" src="https://github.com/merenlab/anvio/assets/197307/f00d4ac3-0822-4d4e-a41e-4cec381bdfe3">

And this is how it would have looked like if it was in Montserrat:

<img width="357" alt="image" src="https://github.com/merenlab/anvio/assets/197307/a8a773b6-633b-4fb4-b2d2-a18d64b81f50">

I'm not sure if it may be because MacOS is missing Montserrat in its default font collection? You can probably solve it by including Montserrat with the anvi'o distribution, but I think it would be much better to not do that and use Helvetica as we did before. Because people will download SVGs to work with anvi'o outputs, and then every font in the SVG will be replaced with Times New Roman just because they don't have Montserrat in their collection.

**Comment by meren** [comment]
It is "anvi'o" (and not capitalized when it occurs in mid-sentence like a regular word). I saw this in multiple places in the interface, and I thought I'd point it it out :)

<img width="237" alt="image" src="https://github.com/merenlab/anvio/assets/197307/f2a5aa8d-5777-451c-a7b2-92520b704cc2">

**Comment by meren** [comment]
In the pangenome, gene cluster functions window looked like this when one clicked on the button in the bins panel:

<img width="1233" alt="image" src="https://github.com/merenlab/anvio/assets/197307/175262d8-9943-424e-b7e6-d0ab060764ec">

And it looks like this now:

<img width="524" alt="image" src="https://github.com/merenlab/anvio/assets/197307/6032e9f3-0a5d-41f3-abc7-2398e6f9e118">

I think the content is much less readable. Please adjust the window and font size to have a comparable view.

**Comment by meren** [comment]
The link here is broken and goes to pull requests page:

<img width="208" alt="image" src="https://github.com/merenlab/anvio/assets/197307/8dc6b6b3-9c1e-4b84-a759-d6a1e860c0e1">

**Comment by meren** [comment]
"Search gene clusters using filters" should have the same size with every other header on this page. 

<img width="398" alt="image" src="https://github.com/merenlab/anvio/assets/197307/0a6a93ce-1128-40b0-bd4b-4d5e77a485f7">

And this section is mean to serve all three search options, but it is not clear anymore:

<img width="486" alt="image" src="https://github.com/merenlab/anvio/assets/197307/acf0f420-82cd-4f65-bada-5b145ae2e6ad">

I'm not sure how to make it obvious now we are not collapsing individual search strategies :/

**Comment by metehaansever** [comment]
> Show grids button doesn't work (as in, you click on it, but grids are not shown for selections):
> 
> <img alt="image" width="302" src="https://private-user-images.githubusercontent.com/197307/288065578-b45a9fe8-c219-4c7f-b12e-5adb01f32e15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjkxMzQsIm5iZiI6MTcwMTg2ODgzNCwicGF0aCI6Ii8xOTczMDcvMjg4MDY1NTc4LWI0NWE5ZmU4LWMyMTktNGM3Zi1iMTJlLTVhZGIwMWYzMmUxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxMzIwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjhmMTkwZWJjODY0MzgyNmI5ZWVjMDNjZjIzMTU5YTQ5NTljNGVjODNiYjI2NmQ4YzZhMjBkZTJjYzMxYmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tOoLFCbF7wFqZWu-2YdnLpzHAVxnLXvylY9obpU_zxQ">
![image](https://github.com/merenlab/anvio/assets/24258998/0ef1605d-b317-4622-b430-944ae5ebc524)

when I test Show Width color and width works for me.

**Comment by metehaansever** [comment]
> > Actually I did that in purpose. I replaced every font with "Montserrat", with some exceptions. The reason for this was to have the same typography everywhere.
> 
> And yet it is not working. This is how it looks on my interface right now:
> 
> <img alt="image" width="385" src="https://private-user-images.githubusercontent.com/197307/288071395-f00d4ac3-0822-4d4e-a41e-4cec381bdfe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzQ5NjEsIm5iZiI6MTcwMTg3NDY2MSwicGF0aCI6Ii8xOTczMDcvMjg4MDcxMzk1LWYwMGQ0YWMzLTA4MjItNGQ0ZS1hNDFlLTRjZWMzODFiZGZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxNDU3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTgxMGVmMDU1ZTZiMzk0M2M1MjQzYzdiYjE4ZGRhMTgwYjFlYTQ3MjdjMjUyNTAxMWYzMDI4MmY4Y2JmMmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QLcOiAtqNlDE7t8WU9ImHz0s2GebmkJuB-hpl7Ma6Vk">
> And this is how it would have looked like if it was in Montserrat:
> 
> <img alt="image" width="357" src="https://private-user-images.githubusercontent.com/197307/288071299-a8a773b6-633b-4fb4-b2d2-a18d64b81f50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzQ5NjEsIm5iZiI6MTcwMTg3NDY2MSwicGF0aCI6Ii8xOTczMDcvMjg4MDcxMjk5LWE4YTc3M2I2LTYzM2ItNGZiNC1iMmQyLWExOGQ2NGI4MWY1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxNDU3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDE5NmUxZWIyMmIxYTI0MWM2MGVlNWM3OWFhYTIzOWE5NjY1MTk1MjU1YjA3OTUzZjE1Y2ZmNjhmMzAzOGVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qq0GthRekAUga6YAHZ1gQ4ZYGlGA1etyfEUcO0OL5ZY">
> I'm not sure if it may be because MacOS is missing Montserrat in its default font collection? You can probably solve it by including Montserrat with the anvi'o distribution, but I think it would be much better to not do that and use Helvetica as we did before. Because people will download SVGs to work with anvi'o outputs, and then every font in the SVG will be replaced with Times New Roman just because they don't have Montserrat in their collection.

I wasn't consider that and Montserrat wasnt one of the default font so I switched all font-family to Helvetica.

**Comment by metehaansever** [comment]
@meren Meren, I fixed every bug in here. I'll run anvio tutorials tomorrow and update here with newer bugs. :feelsgood:

**Comment by meren** [comment]
That's a great point, @xvazquezc. @metehaansever, can you please look into this and figure out if we can display and export SVG images regardless of the font collection on the user side?

Although my top choice among all the [open-source fonts similar to Helvetica](https://www.learnui.design/blog/helvetica-similar-fonts.html) is [Inter](https://fonts.google.com/specimen/Inter), it doesn't have italicised alternative for black 900 (which has been a huge problem for us forever as it is the case with Helvetica). So I think we should go with [Roboto](https://fonts.google.com/specimen/Roboto?preview.text=B.%20fragilis). Can you please make the necessary changes and see if you can display and export SVGs to work with inkscape on them, including on computers without Roboto installed?

**Comment by metehaansever** [comment]
@meren Helvetica is default font for Unix and Macos actually. I tried to Svg export and Helvetica works on my Ubuntu 22.04.
I'll try to embed font-family inside SVG and if its work, i'll update rest with Roboto.

**Comment by xvazquezc** [comment]
@metehaansever maybe other Unix, but definitely not Linux. I've been running Ubuntu by default since 16.04 and it was already missing back then. Definitely still not in 22.04.1... and I prob have more fonts than any sane person. 

![Screenshot at 2023-12-08 15-01-32](https://github.com/merenlab/anvio/assets/14157565/d037e9c0-1584-4081-80f8-b9592eef282f)

Note that even if you tell to use Helvetica, most programs, CSS... will use something else if not available. That's why a good website/CSS normally have a few fonts listed as fallback to limit the differences in appearance if the main font is not available

**Comment by metehaansever** [comment]
> hey @metehaansever , just a small issue I wanted to bring to your attention :)
> 
> ## Issue with tabs for SCG charts in `anvi-display-contigs-stats`
> The program `anvi-display-contigs-stats` shows a chart of single-copy core gene hits at the top, and is a tab for each chart that you can click on to see the data for a specific set of SCGs. Here is how it looks in v8:
> 
> <img alt="image" width="479" src="https://private-user-images.githubusercontent.com/10360586/308168484-7ddf8b48-73b7-496a-82a8-38de6e57d9b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzc5MzQsIm5iZiI6MTcwOTAzNzYzNCwicGF0aCI6Ii8xMDM2MDU4Ni8zMDgxNjg0ODQtN2RkZjhiNDgtNzNiNy00OTZhLTgyYTgtMzhkZTZlNTdkOWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEyNDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDlmNWNlMWFiYTgyY2JiMjRiMzM4ODNiMDgxMTE0ZDA3MzY3YjQ2MTUxZjA2MzRmMmZiYTNhMjY2NzcwOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6svm0iAKPl4TVqx0cPvJCIFSs3JRGsuIRblV9MV9PPQ"> (note that the Protista tab is darker in this screenshot because I had my mouse hovering over it) <img alt="image" width="479" src="https://private-user-images.githubusercontent.com/10360586/308168586-535c14d9-6808-4eb3-ab8b-dbeee1036b27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzc5MzQsIm5iZiI6MTcwOTAzNzYzNCwicGF0aCI6Ii8xMDM2MDU4Ni8zMDgxNjg1ODYtNTM1YzE0ZDktNjgwOC00ZWIzLWFiOGItZGJlZWUxMDM2YjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEyNDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MmVmODMxM2JiOGJkZjQyYTkwMmIyMzgxMjU3MzQwMTI4NmMyNjI4Y2VlN2EwNzRjNzc3NDNlM2IwODBiZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9GE8FzDAX9hZkyE72DpFd7fTCE9Kp4yTM6jL56Fyj4">
> But in the new interface, those tabs have been replaced with links, and it is not obvious which one you are currently looking at: ![image](https://private-user-images.githubusercontent.com/10360586/308168702-9458c45d-6265-4a85-a72a-2cf0d937b0be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzc5MzQsIm5iZiI6MTcwOTAzNzYzNCwicGF0aCI6Ii8xMDM2MDU4Ni8zMDgxNjg3MDItOTQ1OGM0NWQtNjI2NS00YTg1LWE3MmEtMmNmMGQ5MzdiMGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEyNDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZTFkNDFmZTExNGM1YzBiMTI1ZDljNDdiODc0YjdlZDcyZjJmMGY1MjMwOTVlNDQyOGVjOGUzOWU2NTc3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qLJnvNxLJ1N56GoqgONwiIsvFRic1kuFwRlcEWWymSI)

Thank you sharing Iva! I got the problem, i'll fix it asap :)

**Comment by Ge0rges** [comment]
<img width="50" alt="Screenshot 2024-03-05 at 15 23 39" src="https://github.com/merenlab/anvio/assets/3957136/d6e14b4f-1f31-498b-b5bc-f1581bf50d05">

On the left tool bar there is overlapping elements as shown.

Also, could it be an option to have the data tab open on the right as it was before? It was useful to look at Completion/redundancy of a bin along with the data when refining.

**Comment by Ge0rges** [comment]
Also the zoom gesture is somewhat buggy, sometimes it zooms the window, and sometimes the content (and when it does the content it is very fast).

**Comment by metehaansever** [comment]
> <img alt="Screenshot 2024-03-05 at 15 23 39" width="50" src="https://private-user-images.githubusercontent.com/3957136/310308970-d6e14b4f-1f31-498b-b5bc-f1581bf50d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTA2OTksIm5iZiI6MTcxMDQxMDM5OSwicGF0aCI6Ii8zOTU3MTM2LzMxMDMwODk3MC1kNmUxNGI0Zi0xZjMxLTQ5OGItYjViYy1mMTU4MWJmNTBkMDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMDk1OTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTRjYTAwNzY2YjhmNjBkODRiYzY2NGU5MmJmOGFiZWI4YmI0MTZlYzJjMjk1OGRlMjE0ODllNTY1NDU0ODZhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oogUM8697c-qG-toq0nhRpPkv42R_Ptm7WXmEkA4w4o">
> On the left tool bar there is overlapping elements as shown.
> 
> Also, could it be an option to have the data tab open on the right as it was before? It was useful to look at Completion/redundancy of a bin along with the data when refining.

Hello @Ge0rges, I'm wondering what device you use Anvio on. I would like to fix this issue, if you share your resolution. 
So do you have any suggestions regarding Anvio's Zoom behavior? Do you think keeping the old zoom in and zoom out buttons is a solution for a better experience?

**Comment by metehaansever** [comment]
> hey @metehaansever , just a small issue I wanted to bring to your attention :)
> 
> ## Issue with tabs for SCG charts in `anvi-display-contigs-stats`
> The program `anvi-display-contigs-stats` shows a chart of single-copy core gene hits at the top, and is a tab for each chart that you can click on to see the data for a specific set of SCGs. Here is how it looks in v8:
> 
> <img alt="image" width="479" src="https://private-user-images.githubusercontent.com/10360586/308168484-7ddf8b48-73b7-496a-82a8-38de6e57d9b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTA2OTksIm5iZiI6MTcxMDQxMDM5OSwicGF0aCI6Ii8xMDM2MDU4Ni8zMDgxNjg0ODQtN2RkZjhiNDgtNzNiNy00OTZhLTgyYTgtMzhkZTZlNTdkOWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA5NTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NGFkYWNmMWFhMjIwMGRlNTNlYzIwMWIzN2E1ZTU1M2E0ZGUzZjI0NWUxOWFmOTQyMDQ5MjU0MjNhZTcyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._B1OfIyg-6dz4wfqKURdz4Kx0FAHaFiT3KZScqeo88s"> (note that the Protista tab is darker in this screenshot because I had my mouse hovering over it) <img alt="image" width="479" src="https://private-user-images.githubusercontent.com/10360586/308168586-535c14d9-6808-4eb3-ab8b-dbeee1036b27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTA2OTksIm5iZiI6MTcxMDQxMDM5OSwicGF0aCI6Ii8xMDM2MDU4Ni8zMDgxNjg1ODYtNTM1YzE0ZDktNjgwOC00ZWIzLWFiOGItZGJlZWUxMDM2YjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA5NTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZTY2M2NmMDIyMDJkYWZmOGVlZDFkNTUxMjg3MDRlYjliNWMwMGZiOGIzOWIyYzhiMjQ4YzQ2YWI4NTg2NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yS7Xiv9iR3lauFdhtR_GBVwnRsD17wwxtRbr9GOkndM">
> But in the new interface, those tabs have been replaced with links, and it is not obvious which one you are currently looking at: ![image](https://private-user-images.githubusercontent.com/10360586/308168702-9458c45d-6265-4a85-a72a-2cf0d937b0be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTA2OTksIm5iZiI6MTcxMDQxMDM5OSwicGF0aCI6Ii8xMDM2MDU4Ni8zMDgxNjg3MDItOTQ1OGM0NWQtNjI2NS00YTg1LWE3MmEtMmNmMGQ5MzdiMGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA5NTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ODRkZDBhOTdhMzdiMTUwNGJhM2JlMzZjNmExNzFlZGE2OTA4NzdjNjhjZDNhZmI5ZDhmMjE4ODdiM2I0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FQsrJrcI4l_FQokFuzOQrTvrVsbMQcxDaygEuGXB9Og)

![image](https://github.com/merenlab/anvio/assets/24258998/0457c5db-e2e5-4ef1-a758-1540a2e80d6b)
I just fixed it @ivagljiva , I'll merge with 2206-bug-nucleotide branch :)

**Comment by Ge0rges** [comment]
Hi @metehaansever, another suggestion or perhaps more of a question even. Is it possible, (or would it be logical to implement) the option to have this Bin side panel (or the side panel generally) be narrower? In this screenshot for example it's taking up a lot of precious screen real estate.
<img width="1440" alt="Screenshot 2024-03-25 at 09 55 27" src="https://github.com/merenlab/anvio/assets/3957136/5e711c09-3d77-4ea4-80ee-ffa94072cd81">

**Comment by metehaansever** [comment]
@Ge0rges Actually we have more than `S` key, if you wanna take a look at it: https://anvio.org/help/main/artifacts/interactive/

**Comment by Ge0rges** [comment]
I've noticed that sometimes when no splits are selected for a bin, parts of the tree still appear as selected which could be confusing to someone new to Anvi'o. 
<img width="1041" alt="Screenshot 2024-03-26 at 12 42 00" src="https://github.com/merenlab/anvio/assets/3957136/be6c9409-6abd-4e21-9b17-c13d76a99f18">

**Comment by Ge0rges** [comment]
So I just took a random contigs DB and then did this:
- Create a bin
- Add everything to the bin
- By selecting the branches, deselect everything

I could try to make a GIF of this if you can't reproduce.

**Comment by metehaansever** [comment]
> So I just took a random contigs DB and then did this:
> 
> * Create a bin
> * Add everything to the bin
> * By selecting the branches, deselect everything
> 
> I could try to make a GIF of this if you can't reproduce.

I did but its not the case for me. I'll appreciate it f you make a GIF. :smile:

**Comment by Ge0rges** [comment]
Ok I should have specified this was in `anvi-refine` here's the video.

https://github.com/merenlab/anvio/assets/3957136/33ba5947-fd10-45e8-86c0-5d19719c97a9

**Comment by metehaansever** [comment]
> Ok I should have specified this was in `anvi-refine` here's the video.
> 
>  Screen.Recording.2024-03-26.at.13.12.18.mov

It looks like a bug. Probably, if you remove all Bins under `Bin Menu > Delete icon` it will remove them. I'll test it `anvi-refine` with mouse-events. By the way, it works for anvi-interactive. Thanks for catching @Ge0rges :)

**Comment by Ge0rges** [comment]
Potentially another bug @metehaansever, I wonder if you experience this as well. In `anvi-refine`:
- Draw
- Pan plot around (works)
- In Main > Data switch to `Mean coverage Q2Q3`
- Draw
- Pan around doesn't work (although mouse cursor symbol changes)
- Switching data back and redrawing doesn't help.

**Comment by Ge0rges** [comment]
@metehaansever I think a very recent update caused `anvi-summarize` to produce tables with smaller fonts.
<img width="907" alt="Screenshot 2024-03-28 at 13 10 05" src="https://github.com/merenlab/anvio/assets/3957136/4287f17e-ec6a-4077-b78c-47391a1a9535">

**Comment by metehaansever** [comment]
> @metehaansever I think a very recent update caused `anvi-summarize` to produce tables with smaller fonts. <img alt="Screenshot 2024-03-28 at 13 10 05" width="907" src="https://private-user-images.githubusercontent.com/3957136/317817842-4287f17e-ec6a-4077-b78c-47391a1a9535.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NDcwMDYsIm5iZiI6MTcxMTY0NjcwNiwicGF0aCI6Ii8zOTU3MTM2LzMxNzgxNzg0Mi00Mjg3ZjE3ZS1lYzZhLTQwNzctYjc4Yy00NzM5MWExYTk1MzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTcyNTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjNlNjBhNmYxZWUyNmFmMGI0ZWM4NzVmNzVmNTFiYjFiNGJjNmVlMTkzZmZhODE5ODFlMTM4NmNmZDhjODYxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.J4zfGmur49zyNcWgKhYQbMLHCqKuGBaSZ6Mn4lpG9Z8">

I recently adjusted tables in Anvi-Summarize to fit the screen without scrolling. Weird thing is Buttons instead of font-size.
